---
- name: setting Vagrant for CentOS
  hosts: dev_server
  remote_user: vagrant
  sudo: yes
  gather_facts: no

  roles:
    - common
    - yum_repo
    - yum_update
    - git
    - dotfiles
    - zsh
    - tmux
    - vim
    - rbenv
