---
- name: setting vagrant
  hosts: dev_server
  user: vagrant
  sudo: yes
  vars:
    environtment: vagrant
    mysql_port: 3306
    user: vagrant
    branch: master
    src_dir: '/usr/local/src'
    vim_version: '7.4'
    vim_bin_dir: '/usr/local/bin'
    rails_version: '4.2.3'

    rails:
      dir: /var/www/rails/

  roles:
    - common
    - git
    - dotfiles
    - zsh
    - rbenv
    #- mysql
    #- vim
    #- ruby
    #- rails
