---
- name: install dependence packages
  yum:  name={{ item }} state=latest
  with_items:
    - java-1.8.0-openjdk
  tags:
    - yum

- name: download RSense source
  get_url:
    url=http://cx4a.org/pub/rsense/rsense-0.3.tar.bz2
    dest="{{ src_dir }}/rsense-0.3.tar.bz2"

- name: extract RSense source
  unarchive:
    src="{{ src_dir }}/rsense-0.3.tar.bz2"
    dest="{{ src_dir }}"
    copy=no

- name: install RSense
  shell: >
    {{ item }}
    chdir="{{ src_dir }}"
    creates=/usr/local/lib/rsense-0.3/bin/rsense
  with_items:
    - cp -r rsense-0.3 /usr/local/lib
    - chmod +x /usr/local/lib/rsense-0.3/bin/rsense
    - ruby /usr/local/lib/rsense-0.3/etc/config.rb > ~/.rsense
