---
- name: install dependence packages
  yum:  name={{ item }} state=latest
  with_items:
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel
    - zlib-devel
    - perl-ExtUtils-MakeMaker

- name: get git version
  shell: "{{ bin_dir }}/git --version"
  register: installed_git_version
  ignore_errors: True

- name: download git source
  shell: >
    {{ item }}
    chdir="{{ src_dir }}"
  with_items:
    - wget https://www.kernel.org/pub/software/scm/git/git-{{ git_ver }}.tar.gz
    - tar zxvf git-{{ git_ver }}.tar.gz
    - rm -f git-{{ git_ver }}.tar.gz
  when: installed_git_version.stdout != "git version {{ git_ver }}"

- name: install git
  shell: >
    {{ item }}
    chdir="{{ src_dir }}/git-{{ git_ver }}"
  with_items:
   - ./configure --prefix=/usr/local/
   -  make
   -  make install
  when: installed_git_version.stdout != "git version {{ git_ver }}"
