---
- name: install dependence packages
  yum:  name={{ item }} state=latest
  with_items:
    - gcc
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel
    - zlib-devel
    - perl-ExtUtils-MakeMaker
  tags:
    - yum

- name: get git version
  shell: "{{ bin_dir }}/git --version"
  register: installed_git_version
  ignore_errors: True

- name: download git source
  get_url:
    url=https://www.kernel.org/pub/software/scm/git/git-{{ git_ver }}.tar.gz
    dest="{{ src_dir }}/git-{{ git_ver }}.tar.gz"

- name: extract git source
  unarchive:
    src="{{ src_dir }}/git-{{ git_ver }}.tar.gz"
    dest="{{ src_dir }}"
    copy=no

- name: install git
  shell: >
    {{ item }}
    chdir="{{ src_dir }}/git-{{ git_ver }}"
  with_items:
   - ./configure --prefix=/usr/local/
   -  make
   -  make install
  when: installed_git_version.stdout != "git version {{ git_ver }}"
