---
- name: install dependence packages
  yum:  name={{ item }} state=latest
  with_items:
    - ncurses-devel

- name: download zsh source
  shell: |
    wget -O zsh-{{ zsh_ver }}.tar.bz2 http://sourceforge.net/projects/zsh/files/zsh/{{ zsh_ver }}/zsh-{{ zsh_ver }}.tar.bz2/download
    tar jxvf zsh-{{ zsh_ver }}.tar.bz2
    rm -f zsh-{{ zsh_ver }}.tar.bz2
  args:
    chdir: "{{ zsh_src_dir }}"
    creates: "{{ zsh_bin_dir }}/zsh"

- name: install zsh
  shell: |
    cd zsh-{{ zsh_ver }}
    ./configure
    make
    make install
  args:
    chdir: "{{ zsh_src_dir }}"
    creates: "{{ zsh_bin_dir }}/zsh"

- name: install oh-my-zsh
  sudo: no
  git:
    repo=git@github.com:robbyrussell/oh-my-zsh.git
    dest=/home/{{ user }}/.oh-my-zsh
    version={{ branch }}
    accept_hostkey=yes

- name: change shell to zsh
  shell: chsh -s /usr/local/bin/zsh {{ user }}
