---
- name: install dependence packages
  yum:  name={{ item }} state=latest
  with_items:
    - ncurses-devel

- name: download zsh source
  get_url:
    url=http://sourceforge.net/projects/zsh/files/zsh/{{ zsh_ver }}/zsh-{{ zsh_ver }}.tar.bz2/download
    dest="{{ src_dir }}/zsh-{{ zsh_ver }}.tar.bz2"

- name: extract zsh source
  unarchive:
    src="{{ src_dir }}/zsh-{{ zsh_ver }}.tar.bz2"
    dest="{{ src_dir }}"
    copy=no
    creates="{{ src_dir }}/zsh-{{ zsh_ver }}"

- name: install zsh
  shell: >
    {{ item }}
    chdir="{{ src_dir }}/zsh-{{ zsh_ver }}"
    creates="{{ bin_dir }}/zsh"
  with_items:
    - ./configure
    - make
    - make install

- name: install oh-my-zsh
  sudo: no
  git:
    repo=git@github.com:robbyrussell/oh-my-zsh.git
    dest=/home/{{ user }}/.oh-my-zsh

- name: change shell to zsh
  shell: chsh -s {{bin_dir }}/zsh {{ user }}
