---
- name: install MySQL
  yum: name={{ item }}  state=latest
  with_items:
    - mysql
    - mysql-server
    - mysql-devel
  tags:
    - mysgl
    - yum

- name: start mysql-server
  service: name=mysqld state=started enabled=yes
  tags:
    - mysql
