---
- name: install MySQL
  yum: name={{ item }}  state=latest
  with_items:
    - mysql
    - mysql-devel
    - mysql-server
    - MySQL-python
  tags:
    - mysgl
    - yum

- name: start mysql-server
  service: name=mysqld state=started enabled=yes
  tags:
    - mysql

- name: copy .my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 600

- name: set password for root user
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
