# common setting
- name: disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#PermitRootLogin " line="PermitRootLogin no" state=present
  notify: restart sshd
  ignore_errors: yes
- name: disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#PasswordAuthentication " line="PasswordAuthentication no" state=present
  notify: restart sshd
  ignore_errors: yes

# package installation
- name: add EPEL
  sudo: true
  shell: creates=/etc/yum.repos.d/epel.repo rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
- name: yum update
  sudo: true
  yum: name=* state=latest
- name: install basic packages
  sudo: true
  yum: name={{ item }} state=installed
  with_items:
    - git
    - curl
    - wget
    - libselinux-python
    - ruby-devel
    - readline-devel
    - ncurses-devel
    - gdbm-devel
    - openssl-devel
    - libxslt-devel
    - sqlite-devel
    - libyaml
    - libyaml-devel
    - tcl-devel
    - db4-devel
    - libffi-devel
    - gcc
    - libxml2
    - libxml2-devel
    - libxslt
    - libxslt-devel
    - ImageMagick
    - ImageMagick-devel
    - vim

- name: install Development Tool
  sudo: true
  shell: yum -y groupinstall "Development Tools"
